//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGen.exe
//   Version: 1.0.0
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Extension Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UAP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGen - Invoke the following command with a valid 
//   Introspection XML file:
//     AllJoynCodeGen -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace allseen { namespace LSF {

ref class LampStateSignals;

public interface class ILampStateSignals
{
    event Windows::Foundation::TypedEventHandler<LampStateSignals^, LampStateLampStateChangedReceivedEventArgs^>^ LampStateChangedReceived;
};

public ref class LampStateSignals sealed : [Windows::Foundation::Metadata::Default] ILampStateSignals
{
public:
    // Calling this method will send the LampStateChanged signal to every member of the session.
    void LampStateChanged(_In_ Platform::String^ interface_lampID);

    // This event fires whenever the LampStateChanged signal is sent by another member of the session.
    virtual event Windows::Foundation::TypedEventHandler<LampStateSignals^, LampStateLampStateChangedReceivedEventArgs^>^ LampStateChangedReceived;

internal:
    void Initialize(_In_ alljoyn_busobject busObject, _In_ alljoyn_sessionid sessionId);
    void CallLampStateChangedReceived(_In_ LampStateSignals^ sender, _In_ LampStateLampStateChangedReceivedEventArgs^ args);

private:
    alljoyn_busobject m_busObject;
    alljoyn_sessionid m_sessionId;

    alljoyn_interfacedescription_member m_memberLampStateChanged;
};

} } } 
