//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGen.exe
//   Version: 1.0.0
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Extension Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UAP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGen - Invoke the following command with a valid 
//   Introspection XML file:
//     AllJoynCodeGen -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace allseen { namespace LSF {

// Methods
public ref class LampStateTransitionLampStateCalledEventArgs sealed
{
public:
    LampStateTransitionLampStateCalledEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ uint64 interface_timestamp, _In_ Windows::Foundation::Collections::IMapView<Platform::String^,Platform::Object^>^ interface_newState, _In_ uint32 interface_transitionPeriod);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property LampStateTransitionLampStateResult^ Result
    {
        LampStateTransitionLampStateResult^ get() { return m_result; }
        void set(_In_ LampStateTransitionLampStateResult^ value) { m_result = value; }
    }

    property uint64 Timestamp
    {
        uint64 get() { return m_interface_timestamp; }
    }

    property Windows::Foundation::Collections::IMapView<Platform::String^,Platform::Object^>^ NewState
    {
        Windows::Foundation::Collections::IMapView<Platform::String^,Platform::Object^>^ get() { return m_interface_newState; }
    }

    property uint32 TransitionPeriod
    {
        uint32 get() { return m_interface_transitionPeriod; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<LampStateTransitionLampStateResult^>^ GetResultAsync(LampStateTransitionLampStateCalledEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<LampStateTransitionLampStateResult^>
        {
            return t;
        });
    }
    
private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<LampStateTransitionLampStateResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    LampStateTransitionLampStateResult^ m_result;
    uint64 m_interface_timestamp;
    Windows::Foundation::Collections::IMapView<Platform::String^,Platform::Object^>^ m_interface_newState;
    uint32 m_interface_transitionPeriod;
};

public ref class LampStateApplyPulseEffectCalledEventArgs sealed
{
public:
    LampStateApplyPulseEffectCalledEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ Windows::Foundation::Collections::IMapView<Platform::String^,Platform::Object^>^ interface_fromState, _In_ Windows::Foundation::Collections::IMapView<Platform::String^,Platform::Object^>^ interface_toState, _In_ uint32 interface_period, _In_ uint32 interface_duration, _In_ uint32 interface_numPulses, _In_ uint64 interface_timestamp);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property LampStateApplyPulseEffectResult^ Result
    {
        LampStateApplyPulseEffectResult^ get() { return m_result; }
        void set(_In_ LampStateApplyPulseEffectResult^ value) { m_result = value; }
    }

    property Windows::Foundation::Collections::IMapView<Platform::String^,Platform::Object^>^ FromState
    {
        Windows::Foundation::Collections::IMapView<Platform::String^,Platform::Object^>^ get() { return m_interface_fromState; }
    }

    property Windows::Foundation::Collections::IMapView<Platform::String^,Platform::Object^>^ ToState
    {
        Windows::Foundation::Collections::IMapView<Platform::String^,Platform::Object^>^ get() { return m_interface_toState; }
    }

    property uint32 Period
    {
        uint32 get() { return m_interface_period; }
    }

    property uint32 Duration
    {
        uint32 get() { return m_interface_duration; }
    }

    property uint32 NumPulses
    {
        uint32 get() { return m_interface_numPulses; }
    }

    property uint64 Timestamp
    {
        uint64 get() { return m_interface_timestamp; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<LampStateApplyPulseEffectResult^>^ GetResultAsync(LampStateApplyPulseEffectCalledEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<LampStateApplyPulseEffectResult^>
        {
            return t;
        });
    }
    
private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<LampStateApplyPulseEffectResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    LampStateApplyPulseEffectResult^ m_result;
    Windows::Foundation::Collections::IMapView<Platform::String^,Platform::Object^>^ m_interface_fromState;
    Windows::Foundation::Collections::IMapView<Platform::String^,Platform::Object^>^ m_interface_toState;
    uint32 m_interface_period;
    uint32 m_interface_duration;
    uint32 m_interface_numPulses;
    uint64 m_interface_timestamp;
};

// Readable Properties
public ref class LampStateGetVersionRequestedEventArgs sealed
{
public:
    LampStateGetVersionRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property LampStateGetVersionResult^ Result
    {
        LampStateGetVersionResult^ get() { return m_result; }
        void set(_In_ LampStateGetVersionResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<LampStateGetVersionResult^>^ GetResultAsync(LampStateGetVersionRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<LampStateGetVersionResult^>
        {
            return t;
        });
    }

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<LampStateGetVersionResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    LampStateGetVersionResult^ m_result;
};

public ref class LampStateGetOnOffRequestedEventArgs sealed
{
public:
    LampStateGetOnOffRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property LampStateGetOnOffResult^ Result
    {
        LampStateGetOnOffResult^ get() { return m_result; }
        void set(_In_ LampStateGetOnOffResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<LampStateGetOnOffResult^>^ GetResultAsync(LampStateGetOnOffRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<LampStateGetOnOffResult^>
        {
            return t;
        });
    }

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<LampStateGetOnOffResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    LampStateGetOnOffResult^ m_result;
};

public ref class LampStateGetHueRequestedEventArgs sealed
{
public:
    LampStateGetHueRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property LampStateGetHueResult^ Result
    {
        LampStateGetHueResult^ get() { return m_result; }
        void set(_In_ LampStateGetHueResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<LampStateGetHueResult^>^ GetResultAsync(LampStateGetHueRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<LampStateGetHueResult^>
        {
            return t;
        });
    }

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<LampStateGetHueResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    LampStateGetHueResult^ m_result;
};

public ref class LampStateGetSaturationRequestedEventArgs sealed
{
public:
    LampStateGetSaturationRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property LampStateGetSaturationResult^ Result
    {
        LampStateGetSaturationResult^ get() { return m_result; }
        void set(_In_ LampStateGetSaturationResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<LampStateGetSaturationResult^>^ GetResultAsync(LampStateGetSaturationRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<LampStateGetSaturationResult^>
        {
            return t;
        });
    }

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<LampStateGetSaturationResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    LampStateGetSaturationResult^ m_result;
};

public ref class LampStateGetColorTempRequestedEventArgs sealed
{
public:
    LampStateGetColorTempRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property LampStateGetColorTempResult^ Result
    {
        LampStateGetColorTempResult^ get() { return m_result; }
        void set(_In_ LampStateGetColorTempResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<LampStateGetColorTempResult^>^ GetResultAsync(LampStateGetColorTempRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<LampStateGetColorTempResult^>
        {
            return t;
        });
    }

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<LampStateGetColorTempResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    LampStateGetColorTempResult^ m_result;
};

public ref class LampStateGetBrightnessRequestedEventArgs sealed
{
public:
    LampStateGetBrightnessRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property LampStateGetBrightnessResult^ Result
    {
        LampStateGetBrightnessResult^ get() { return m_result; }
        void set(_In_ LampStateGetBrightnessResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<LampStateGetBrightnessResult^>^ GetResultAsync(LampStateGetBrightnessRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<LampStateGetBrightnessResult^>
        {
            return t;
        });
    }

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<LampStateGetBrightnessResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    LampStateGetBrightnessResult^ m_result;
};

// Writable Properties
public ref class LampStateSetOnOffRequestedEventArgs sealed
{
public:
    LampStateSetOnOffRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ bool value);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property bool Value
    {
        bool get() { return m_value; }
    }

    property int ResultStatus
    {
        int get() { return m_resultStatus; }
        void set(_In_ int value) { m_resultStatus = value; }
    }

    static Windows::Foundation::IAsyncOperation<int>^ GetResultAsync(LampStateSetOnOffRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<int>
        {
            return t;
        });
    }

    Windows::Foundation::Deferral^ GetDeferral();

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<int> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    bool m_value;
    int m_resultStatus;
};

public ref class LampStateSetHueRequestedEventArgs sealed
{
public:
    LampStateSetHueRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ uint32 value);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property uint32 Value
    {
        uint32 get() { return m_value; }
    }

    property int ResultStatus
    {
        int get() { return m_resultStatus; }
        void set(_In_ int value) { m_resultStatus = value; }
    }

    static Windows::Foundation::IAsyncOperation<int>^ GetResultAsync(LampStateSetHueRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<int>
        {
            return t;
        });
    }

    Windows::Foundation::Deferral^ GetDeferral();

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<int> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    uint32 m_value;
    int m_resultStatus;
};

public ref class LampStateSetSaturationRequestedEventArgs sealed
{
public:
    LampStateSetSaturationRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ uint32 value);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property uint32 Value
    {
        uint32 get() { return m_value; }
    }

    property int ResultStatus
    {
        int get() { return m_resultStatus; }
        void set(_In_ int value) { m_resultStatus = value; }
    }

    static Windows::Foundation::IAsyncOperation<int>^ GetResultAsync(LampStateSetSaturationRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<int>
        {
            return t;
        });
    }

    Windows::Foundation::Deferral^ GetDeferral();

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<int> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    uint32 m_value;
    int m_resultStatus;
};

public ref class LampStateSetColorTempRequestedEventArgs sealed
{
public:
    LampStateSetColorTempRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ uint32 value);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property uint32 Value
    {
        uint32 get() { return m_value; }
    }

    property int ResultStatus
    {
        int get() { return m_resultStatus; }
        void set(_In_ int value) { m_resultStatus = value; }
    }

    static Windows::Foundation::IAsyncOperation<int>^ GetResultAsync(LampStateSetColorTempRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<int>
        {
            return t;
        });
    }

    Windows::Foundation::Deferral^ GetDeferral();

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<int> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    uint32 m_value;
    int m_resultStatus;
};

public ref class LampStateSetBrightnessRequestedEventArgs sealed
{
public:
    LampStateSetBrightnessRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ uint32 value);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property uint32 Value
    {
        uint32 get() { return m_value; }
    }

    property int ResultStatus
    {
        int get() { return m_resultStatus; }
        void set(_In_ int value) { m_resultStatus = value; }
    }

    static Windows::Foundation::IAsyncOperation<int>^ GetResultAsync(LampStateSetBrightnessRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<int>
        {
            return t;
        });
    }

    Windows::Foundation::Deferral^ GetDeferral();

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<int> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    uint32 m_value;
    int m_resultStatus;
};

} } } 
