//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGen.exe
//   Version: 1.0.0
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Extension Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UAP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGen - Invoke the following command with a valid 
//   Introspection XML file:
//     AllJoynCodeGen -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace allseen { namespace LSF {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement ILampDetailsService. Instead, LampDetailsServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class LampDetailsServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] ILampDetailsService
{
public:
    // Method Invocation Events

    // Property Read Events
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetVersionRequestedEventArgs^>^ GetVersionRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetMakeRequestedEventArgs^>^ GetMakeRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetModelRequestedEventArgs^>^ GetModelRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetTypeRequestedEventArgs^>^ GetTypeRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetLampTypeRequestedEventArgs^>^ GetLampTypeRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetLampBaseTypeRequestedEventArgs^>^ GetLampBaseTypeRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetLampBeamAngleRequestedEventArgs^>^ GetLampBeamAngleRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetDimmableRequestedEventArgs^>^ GetDimmableRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetColorRequestedEventArgs^>^ GetColorRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetVariableColorTempRequestedEventArgs^>^ GetVariableColorTempRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetHasEffectsRequestedEventArgs^>^ GetHasEffectsRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetMinVoltageRequestedEventArgs^>^ GetMinVoltageRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetMaxVoltageRequestedEventArgs^>^ GetMaxVoltageRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetWattageRequestedEventArgs^>^ GetWattageRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetIncandescentEquivalentRequestedEventArgs^>^ GetIncandescentEquivalentRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetMaxLumensRequestedEventArgs^>^ GetMaxLumensRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetMinTemperatureRequestedEventArgs^>^ GetMinTemperatureRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetMaxTemperatureRequestedEventArgs^>^ GetMaxTemperatureRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetColorRenderingIndexRequestedEventArgs^>^ GetColorRenderingIndexRequested;
    event Windows::Foundation::TypedEventHandler<LampDetailsServiceEventAdapter^, LampDetailsGetLampIDRequestedEventArgs^>^ GetLampIDRequested;
    
    // Property Write Events

    // ILampDetailsService Implementation

    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetVersionResult^>^ GetVersionAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetMakeResult^>^ GetMakeAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetModelResult^>^ GetModelAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetTypeResult^>^ GetTypeAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetLampTypeResult^>^ GetLampTypeAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetLampBaseTypeResult^>^ GetLampBaseTypeAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetLampBeamAngleResult^>^ GetLampBeamAngleAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetDimmableResult^>^ GetDimmableAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetColorResult^>^ GetColorAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetVariableColorTempResult^>^ GetVariableColorTempAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetHasEffectsResult^>^ GetHasEffectsAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetMinVoltageResult^>^ GetMinVoltageAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetMaxVoltageResult^>^ GetMaxVoltageAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetWattageResult^>^ GetWattageAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetIncandescentEquivalentResult^>^ GetIncandescentEquivalentAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetMaxLumensResult^>^ GetMaxLumensAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetMinTemperatureResult^>^ GetMinTemperatureAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetMaxTemperatureResult^>^ GetMaxTemperatureAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetColorRenderingIndexResult^>^ GetColorRenderingIndexAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampDetailsGetLampIDResult^>^ GetLampIDAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

};

} } } 
