//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGen.exe
//   Version: 1.0.0
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Extension Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UAP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGen - Invoke the following command with a valid 
//   Introspection XML file:
//     AllJoynCodeGen -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

#include <windows.h>
#include <ppltasks.h>
#include <concrt.h>
#include <collection.h>
#include <windows.devices.alljoyn.interop.h>
#include <map>

#include <alljoyn_c/busattachment.h>
#include <alljoyn_c/dbusstddefines.h>
#include <alljoyn_c/AboutData.h>
#include <alljoyn_c/AboutObj.h>
#include <alljoyn_c/AboutObjectDescription.h>

#include "AllJoynHelpers.h"
#define PROJECT_NAMESPACE org::allseen::LSF
#include "LampServiceStructures.h"
#include "LampParametersStructures.h"
#include "LampDetailsStructures.h"
#include "LampStateStructures.h"
#include "TypeConversionHelpers.h"

#include "LampServiceMethodResults.h"
#include "LampServiceEventArgs.h"
#include "ILampServiceService.h"
#include "LampServiceSignals.h"
#include "LampServiceProducer.h"
#include "LampServiceWatcher.h"
#include "LampServiceConsumer.h"
#include "LampServiceServiceEventArgs.h"
#include "LampServiceServiceEventAdapter.h"

#include "LampParametersMethodResults.h"
#include "LampParametersEventArgs.h"
#include "ILampParametersService.h"
#include "LampParametersSignals.h"
#include "LampParametersProducer.h"
#include "LampParametersWatcher.h"
#include "LampParametersConsumer.h"
#include "LampParametersServiceEventArgs.h"
#include "LampParametersServiceEventAdapter.h"

#include "LampDetailsMethodResults.h"
#include "LampDetailsEventArgs.h"
#include "ILampDetailsService.h"
#include "LampDetailsSignals.h"
#include "LampDetailsProducer.h"
#include "LampDetailsWatcher.h"
#include "LampDetailsConsumer.h"
#include "LampDetailsServiceEventArgs.h"
#include "LampDetailsServiceEventAdapter.h"

#include "LampStateMethodResults.h"
#include "LampStateEventArgs.h"
#include "ILampStateService.h"
#include "LampStateSignals.h"
#include "LampStateProducer.h"
#include "LampStateWatcher.h"
#include "LampStateConsumer.h"
#include "LampStateServiceEventArgs.h"
#include "LampStateServiceEventAdapter.h"

